scenario:
    eraa_version: '2023' # possible versions 2022, 2023
    climatic_years: 'all' # either list of years or 'all'. If 'all' climatic_year_from/to must be given
    target_years: [2030] #, 2030]
    climatic_year_from: 1982 # 1982 for ERAA 2023, 1985 for ERAA 2022
    climatic_year_to: 2017 # 2017 for ERAA 2023, 2016 for ERAA 2022

climatic_data_sources: [ # climatic data source additionally to PECD \in ['Reading', 'ninja']
#    "ninja",
#    'Reading'
]

PECD_alternatives:
    include: [] #['Existing', 'SP199_HH100_A', 'SP199_HH100_B', 'SP199_HH100_C', 'SP199_HH150_A', 'SP199_HH150_B', 'SP199_HH150_C', 'SP199_HH200_A', 'SP199_HH200_B', 'SP199_HH200_C']
    dir: '' #'pypsa-eraa/resources/PECD_alternatives/'

solve:
    solve: true
