scenario:
    climatic_years: [2010]
    target_years: [2027, 2030]
    climatic_year_from: 1983
    climatic_year_to: 2017

climatic_data_sources: [
    "pecd", "reading", "ninja"
]

model: "remix"
