scenario:
    climatic_years: [2000]
    target_years: [2027, 2030]
    climatic_year_from: 1982
    climatic_year_to: 2016

climatic_data_sources: [
    "pecd", "reading", "ninja"
]

model: "pypsa"
